version: '3.8'

services:
  # Demo MSSQL Server for testing
  mssql-demo:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: locodex-mssql-demo
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LocoDex123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-demo-data:/var/opt/mssql
    networks:
      - locodex-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P LocoDex123! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mssql-demo-data:
    driver: local

networks:
  locodex-network:
    external: true