apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: locodex
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
    
    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Kubernetes API server
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
      
      # Kubernetes nodes
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
      
      # Kubernetes pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
      
      # LocoDex AI Agent
      - job_name: 'locodex-ai-agent'
        static_configs:
          - targets: ['locodex-ai-agent:3001']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # LocoDex Deep Research Service
      - job_name: 'locodex-deep-research'
        static_configs:
          - targets: ['locodex-deep-research:8001']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # LocoDex DeepSearch Service
      - job_name: 'locodex-deepsearch'
        static_configs:
          - targets: ['locodex-deepsearch:8000']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # Redis
      - job_name: 'redis'
        static_configs:
          - targets: ['locodex-redis:6379']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # MongoDB
      - job_name: 'mongodb'
        static_configs:
          - targets: ['locodex-mongodb:27017']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # Elasticsearch
      - job_name: 'elasticsearch'
        static_configs:
          - targets: ['locodex-elasticsearch:9200']
        metrics_path: '/_prometheus/metrics'
        scrape_interval: 30s
      
      # Nginx
      - job_name: 'nginx'
        static_configs:
          - targets: ['locodex-nginx:80']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # MinIO
      - job_name: 'minio'
        static_configs:
          - targets: ['locodex-minio:9000']
        metrics_path: '/minio/v2/metrics/cluster'
        scrape_interval: 30s
      
      # Jaeger
      - job_name: 'jaeger'
        static_configs:
          - targets: ['locodex-jaeger:14269']
        metrics_path: '/metrics'
        scrape_interval: 30s